# Ingress
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: 34-79-26-124.nip.io
      paths:
      - "/"
# Secret
db:
  rootpassword: root
  userpassword: patodegoma
  username: keepcoding

# Configmap
dbname: contador-db
host: mysql-db

# Deployment
replicaCount: 1
affinity: 
  enabled: true
  content:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: layer
              operator: In
              values:
              - db
          topologyKey: "kubernetes.io/hostname"
    podAntiAffinity:          
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: layer
                operator: In
                values:
                - db
            topologyKey: "kubernetes.io/hostname"

image:
  app: "carlosfeufernandez/contador-visitantes:v1"
  db: "mysql:latest"
  pullPolicy: IfNotPresent

# Service
service:
  type: "LoadBalancer"
  app: 5000
  port: 3306

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  pct: 70
