version: '3.9'

services:
  app:
    environment:
      MYSQL_DB: "contador-db"
      MYSQL_USER: "keepcoding"
      MYSQL_PASSWORD: "patodegoma"
      MYSQL_HOST: "mysql-db"
    build: .
    ports:
     - 5000:5000
    depends_on:
      - mysql-db
    volumes:
      - ./app.py:/app/app.py
  mysql-db:
    image: mysql
    environment:
     MYSQL_ROOT_PASSWORD: "root"
     MYSQL_DATABASE: "contador-db"
     MYSQL_USER: "keepcoding"
     MYSQL_PASSWORD: "patodegoma"
    volumes:
     - "./db.sh:/docker-entrypoint-initdb.d/db.sh"
     - "mysql-data:/var/lib/mysql"

volumes:
 mysql-data: