apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: counter-ha
  namespace: counter-app-db
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: counterapp-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70