apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: counter-app-db
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

 apiVersion: v1
 kind: PersistentVolume
 metadata:
   namespace: counter-app-db
   name: mysql-pv
 spec:
   accessModes:
     - ReadWriteOnce
   capacity:
     storage: 1Gi
   hostPath:
     path: var/lib/mysql