apiVersion: v1
data:
  dbname: {{ .Values.dbname }}
  host: {{ include "counter-app.fullname" . }}-db
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ include "counter-app.fullname" . }}-cm
  namespace: {{ .Release.Namespace }}