{{- $name := include "counter-app.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - pathType: Prefix
            path: {{ . | quote }}
            backend:
              service:
                name: {{ $name }}-app
                port:
                  number: 5000
      {{- end }}
  {{- end }}