apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "counter-app.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "counter-app.selectorLabels" . | nindent 6 }}
      layer: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "counter-app.selectorLabels" . | nindent 8 }}
        layer: db
    spec:
      containers:
      - image: {{ .Values.image.db }}
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "counter-app.fullname" . }}-secret
              key: rootpassword
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ include "counter-app.fullname" . }}-cm
              key: dbname
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "counter-app.fullname" . }}-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "counter-app.fullname" . }}-secret
              key: userpassword
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
      - name: mysql-pvc
        persistentVolumeClaim:
          claimName: {{ include "counter-app.fullname" . }}-mysql-pvc
      - name: mysql-initdb
        configMap:
            name: mysql-initdb
            items:
              - key: db.sh
                path: db.sh
            defaultMode: 0555