apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "counter-app.fullname" . }}-mysql-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi