apiVersion: v1
kind: Service
metadata:
  name: {{ include "counter-app.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "counter-app.labels" . | nindent 4 }}-app
spec:
  ports:
  - port: {{ .Values.service.app }}
    protocol: TCP
    targetPort: 5000
  selector:
    {{- include "counter-app.selectorLabels" . | nindent 4 }}
    layer: app
  type: {{ .Values.service.type }}
